export const AppConfig = {
	site_name: 'Nexus-Japan Blog',
	title: 'Nexus Blog',
	description: 'Nexus Japan Blog is a knowledge sharing website.',
	url: 'https://Nexus-Japan.github.io',
	locale: 'ja',
	author: 'Nexus Japan',
	copyright: '©Nexus Japan Some Rights Reserved',
	pagination_size: 10,
	contacts: {
		email: '',
		facebook: '',
		telegram: '',
		twitter: '',
		github: 'Nexus-Japan',
		rss: '',
		vkontakte: '',
		linkedin: '',
		instagram: '',
		line: '',
		gitlab: '',
		weibo: '',
		codepen: '',
		youtube: '',
		soundcloud: '',
		medium: '',
	},
};
